name: Deploy Surge

on:
  pull_request:
  push:
    branches: 
      - master
      - develop

jobs:
  test:
    name: Deploying to surge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install NodeJS
        uses: actions/setup-node@v1
      - name: Build the website
        with:
          node-version: 12
          name: Install Surge
          run: npm install -g surge
          run: surge ./bootcamp-newapps.surge.sh --token ${{secrets.SURGE_TOKEN}}
